### ISSUE TITLE
Is it possible to use this and host a series of float data (like a slave that has data in its holding registers for a master to read)?

### ISSUE THREAD

**Issue by AtharZafeer** [jandrassy/IsgModbusTcpSG#1]
I am quite new to this and am trying to understand modbus. I understand how you have implemented to match the modbus protocol. But, i am wondering is there a way to host the data for other master devices to read from my esp32 module and encj28j60 module?

I also found out that UIP library supports esp32. So, that shouldnt be a problem. I am just wondering if there is a way to have data that can be read by external master devices

**Comment by JAndrassy** [comment]
Modbus TCP has client and server (RTU has master and slave). 
the registers are on server.
this code is a TCP client
